config/routes.rb
Rails.application.routes.draw do
  get 'configs/show'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :devices do
    get :difference
  end

  resources :configs

  resources :connection_profiles

  root 'devices#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/config.rb
class Config < ApplicationRecord
  belongs_to :device
end

app/models/connection_profile.rb
class ConnectionProfile < ApplicationRecord
  has_many :devices
end

app/models/device.rb
class Device < ApplicationRecord
  has_many :configs
  belongs_to :connection_profile
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/configs_controller.rb
class ConfigsController < ApplicationController
  before_action :set_config, only: [:show, :destroy]

  def show; end

  def destroy
    @config.destroy
    redirect_to device_path(@config.device_id)
  end

  private

  def set_config
    @config = Config.find(params[:id])
  end
end

app/controllers/connection_profiles_controller.rb
class ConnectionProfilesController < ApplicationController
  before_action :set_connection_profile, only: [:show, :edit, :update, :destroy]

  def index
    @connection_profiles = ConnectionProfile.all  
  end

  def new
    @connection_profile = ConnectionProfile.new
  end

  def create 
    @connection_profile = ConnectionProfile.new(connection_profile_params)

    if @connection_profile.save
      redirect_to @connection_profile
    end
  end

  def edit; end
  def show; end

  def update
    if @connection_profile.update(connection_profile_params)
      redirect_to @connection_profile
    end
  end

  private
  
  def connection_profile_params
    params.require(:connection_profile).permit(:name, :username, :password)
  end

  def set_connection_profile
    @connection_profile = ConnectionProfile.find(params[:id])
  end
end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController
  before_action :set_device, only: [:show, :edit, :destroy, :update]

  def index
    @devices = Device.all
  end

  def new
    @device = Device.new
  end

  def create
    @device = Device.new(device_params)

    if @device.save
      redirect_to @device
    else
      render :new
    end
  end

  def show; end

  def edit; end

  def update; end

  def destroy
    @device.destroy
    redirect_to device_path
  end

  def difference
    z = params[:conf_ids]
    @config_1 = Config.find(z[0].to_i)
    @config_2 = Config.find(z[1].to_i)
    @x = Diffy::SplitDiff.new(@config_1.config, @config_2.config, :format => :html)
  end

  private

  def set_device
    @device = Device.find(params[:id])
  end

  def device_params
    params.require(:device).permit(:hostname, :ip, :connection_profile_id, conf_ids: [] )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/configs_helper.rb
module ConfigsHelper
end

app/helpers/connection_profiles_helper.rb
module ConnectionProfilesHelper
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/views/configs/show.html.erb
<h1>Config of <%= @config.device.hostname %> created at: <%= @config.created_at %> </h1>
<p><%= raw(@config.config.gsub(/\n/, '<br/>'.html_safe)) %></p>

app/views/connection_profiles/edit.html.erb
<h2>
	<strong>
		Edit connection profile
	</strong>
</h2>
<%= form_for @connection_profile do |f| %>
	<div class="row">
		<div class="col-md-1">
			<%= f.label :name %>
		</div>
		<div class="col-md-1">
			<%= f.text_field :name %>
		</div>
	</div>
	<div class="row">
		<div class="col-md-1">
			<%= f.label :username %>
		</div>
		<div class="col-md-1">
			<%= f.text_field :username %>
		</div>
	</div>
	<div class="row">
		<div class="col-md-1">
			<%= f.label :password %>
		</div>
		<div class="col-md-1">
			<%= f.text_field :password %>
		</div>
	</div>
	<div class="row">
		<div class="col-md-1">
			<div class="action">
				<%= f.submit 'Change', class: "btn btn-default" %>
			</div>
		</div> 
	</div>
<% end %>

app/views/connection_profiles/index.html.erb
<h2>
	<strong>List of connection profiles</strong>
</h2>	
<p>
	<% @connection_profiles.each do |profile| %>
		<p><%= link_to "#{profile.name}", connection_profile_path(profile) %></p>
	<% end %>

<%= link_to 'Add connection profile',  new_connection_profile_path %>
</p>

app/views/connection_profiles/new.html.erb
<h2>
	<strong>
		Create connection profile
	</strong>
</h2>
<%= form_for @connection_profile do |f| %>
	<div class="row">
		<div class="col-md-1">
			<%= f.label :name %>
		</div>
		<div class="col-md-1">
			<%= f.text_field :name %>
		</div>
	</div>
	<div class="row">
		<div class="col-md-1">
			<%= f.label :username %>
		</div>
		<div class="col-md-1">
			<%= f.text_field :username %>
		</div>
	</div>
	<div class="row">
		<div class="col-md-1">
			<%= f.label :password %>
		</div>
		<div class="col-md-1">
			<%= f.text_field :password %>
		</div>
	</div>
	<div class="row">
		<div class="col-md-1">
			<div class="action">
				<%= f.submit 'Create', class: "btn btn-default" %>
			</div>
		</div> 
	</div>
<% end %>

app/views/connection_profiles/show.html.erb
<h2>
	<strong>
		Profile name: <%= @connection_profile.name %>
	</strong>
</h2>
<p>
	Username for login:<i> <%= @connection_profile.username %></i>	
</p>
<p>
	Password for login:<i> <%= @connection_profile.password %></i>
</p>

<%= link_to 'Change', edit_connection_profile_path(@connection_profile) %>



app/views/devices/difference.html.erb
<div class="row">
	<div class="col-lg-6"><%= raw(@x.left) %></div>
	<div class="col-lg-6"><%= raw(@x.right) %></div>
</div>

app/views/devices/index.html.erb
<div>
	<div>
		<h3>
			<b>List of all devices</b>
		</h3>
	</div>
	<% @devices.each do |device| %>
	  <%= link_to "#{device.hostname}", device_path(device) %> <br/>
	<% end %>
	<br/>
	<strong>
		<%= link_to "Add device", new_device_path %>
	</strong>
</div>

app/views/devices/new.html.erb
<div class="form">
  <div class="row">
    <%= form_for(@device) do |f| %>
      <div class="col-md-2">
        <%= f.label :hostname %>
      </div>
      <div class="col-md-2">
        <%= f.text_field :hostname %>
      </div>
  </div>
  <div class="row">
      <div class="col-md-2">
      <%= f.label :ip %>
      </div>
      <div class="col-md-2">
      <%= f.text_field :ip %>
      </div>
  </div>

  <div class="row">
    <div class="col-md-2">
      <%= f.label :connection_profile_id, "List of profies" %>
    </div>
    <div class="col-md-2">  
      <%= f.collection_select :connection_profile_id, ConnectionProfile.all, :id, :name, {}%>
    </div>
  </div>  

    <div class="row">
      <div class="col-md-4">
        <div class="action">
          <%= f.submit 'Create', class: "btn btn-default" %>
        </div>
      </div> 
    </div>
  <% end %>
</div>

app/views/devices/show.html.erb
<p>
  <strong><%= @device.hostname %></strong>
</p>
<p>
  <% if @device.configs.empty? %>
    <i>Конфигурации появятся позднее</i>
  <% else %>
  	<%= form_tag  device_difference_path(@device), method: :get do %>	   
	    <% i = 0 %>
	    <% @device.configs.each do |config| %>
	      <ul><li>
	      |
	      <%= check_box_tag "conf_ids[]", config.id %>
	      <%= link_to "#{config.created_at}", config_path(config) %> |
	      <%= link_to 'Удалить',  config, method: :delete, data: { confirm: 'Вы уверены?' } %></li></ul> 
	      
	    <% end %>
	    <%= submit_tag 'сравнить'%>
	<% end %>
  <% end %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "CiscoConfig" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">CiscoConfig</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Devices", devices_path  %></li>
            <li><%= link_to "Profiles", connection_profiles_path  %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; YOBA development 2016</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/layouts/application.html.erb.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "CiscoConfig" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">CiscoConfig</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Link1", "/path1"  %></li>
            <li><%= link_to "Link2", "/path2"  %></li>
            <li><%= link_to "Link3", "/path3"  %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-lg-3">
          <div class="well sidebar-nav">
            <h3>Sidebar</h3>
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2016</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>